/**
 * OSPlus chat/ping relay + HTTP services
 * ---------------------------------------
 * Three responsibilities under one process:
 *
 *   1. WebSocket chat/ping fanout — room-scoped, ephemeral, no persistence.
 *      Rooms vanish on process restart by design.
 *
 *   2. REST API (`/api/*`) for per-install profile rows + auth tokens. Backed
 *      by `data/osplus.sqlite3` via the persistence module in `server/api/`.
 *      Boundary discipline: only `api.handleHttp(req, res)` is called from
 *      this file; the DB instance is owned by that module.
 *
 *   3. Public GET `/updates/latest`, a short-lived in-memory projection of
 *      the latest stable GitHub Release. No auth and no persistence.
 *
 * Deployment:
 *   - Bound to 127.0.0.1; reverse-proxied by Caddy on the public TLS endpoint.
 *   - systemd unit at server/deploy/osplus-relay.service.
 *   - Runs as the unprivileged `osplus` user.
 *   - SQLite DB at $OSPLUS_DATA_DIR/osplus.sqlite3 (default: ./data).
 *
 * WS hardening (baseline; not a substitute for real auth):
 *   - 4 KB max payload (ws-level)
 *   - 5 connections per source IP
 *   - 5 messages/sec per connection (drop on violation)
 *   - Strict message-shape validation
 *   - Room codes constrained to /^[A-Z0-9]{4,16}$/ (covers shareable 4-char codes
 *     and mod-derived match codes from `CurrentMatchSeed`)
 *   - Chat text: control chars stripped, capped at 500 chars
 *   - Optional shared-secret token via RELAY_TOKEN env var
 *
 * REST auth (`/api/*`): per-install bearer tokens TOFU-bound to a Prometheus ID
 * at first contact; see `server/api/middleware/auth.js` and ADR 0002 A-2. The
 * `RELAY_TOKEN` above is unrelated to REST auth — it gates WS connections only.
 */

const http = require("http");
const path = require("path");
const { WebSocketServer } = require("ws");
const { createApi } = require("./api");
const {
  DEFAULT_ASSET_NAME,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_REPO,
  createUpdates,
} = require("./updates");

// === Configuration ============================================================

const PORT          = parseInt(process.env.PORT || "3000", 10);
const HOST          = process.env.HOST || "127.0.0.1";
const RELAY_TOKEN   = process.env.RELAY_TOKEN || "";
const TRUST_PROXY   = process.env.TRUST_PROXY === "1";
const DATA_DIR      = process.env.OSPLUS_DATA_DIR || path.join(__dirname, "data");
const RELEASE_REPO  = process.env.OSPLUS_RELEASE_REPO || DEFAULT_REPO;
const RELEASE_ASSET = process.env.OSPLUS_RELEASE_ASSET || DEFAULT_ASSET_NAME;
const RELEASE_CACHE_TTL_MS = parsePositiveInt(
  process.env.OSPLUS_RELEASE_CACHE_TTL_MS,
  DEFAULT_CACHE_TTL_MS,
);
const RELEASE_OVERRIDE_VERSION = process.env.OSPLUS_RELEASE_OVERRIDE_VERSION || "";
const GITHUB_TOKEN = process.env.OSPLUS_GITHUB_TOKEN || "";

// === Limits ===================================================================

const MAX_PAYLOAD_BYTES = 4 * 1024;
const MAX_CONNS_PER_IP  = 5;
const MAX_MSG_RATE      = 5;
const RATE_WINDOW_MS    = 1000;
const MAX_CHAT_LENGTH   = 500;
const MAX_USERNAME_LEN  = 32;
// Two flavors of room code coexist:
//   1. Human-shareable codes generated by generateRoomCode() — exactly 4 chars
//      from the Crockford-ish alphabet [A-Z2-9] (no 0/1/I/O to avoid look-alikes).
//   2. Mod-derived codes from the Lua client.
//      New clients send only the 8-char seed code; older clients may still
//      send a `<seed>T<team>` code during rollout.
// The validator just needs to reject control chars / whitespace / smuggled
// delimiters; it isn't the place to enforce a specific codec. Hence the
// permissive bound below and the separate alphabet inside generateRoomCode.
const ROOM_CODE_RE      = /^[A-Z0-9]{4,16}$/;
const VALID_TYPES       = new Set(["join", "leave", "ping", "chat"]);
// `presence` is server-out-only and intentionally omitted from VALID_TYPES;
// clients should never send it.

// === State ====================================================================

const rooms        = new Map(); // roomCode -> Set<ws>
const connsPerIp   = new Map(); // ip -> count

// === Helpers ==================================================================

function log(msg) {
  console.log(`${new Date().toISOString()} ${msg}`);
}

function parsePositiveInt(raw, fallback) {
  if (raw === undefined || raw === null || raw === "") return fallback;
  const parsed = Number(raw);
  return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function getClientIp(req) {
  if (TRUST_PROXY) {
    const xff = req.headers["x-forwarded-for"];
    if (xff) return xff.split(",")[0].trim();
  }
  return req.socket.remoteAddress || "unknown";
}

function generateRoomCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "";
  for (let i = 0; i < 4; i++) code += chars[Math.floor(Math.random() * chars.length)];
  return code;
}

function sanitizeChatText(s) {
  if (typeof s !== "string") return "";
  return s.replace(/[\x00-\x08\x0B-\x1F\x7F]/g, "").slice(0, MAX_CHAT_LENGTH);
}

function sanitizeUsername(s) {
  if (typeof s !== "string") return "Anonymous";
  // Strip ALL C0 controls (0x00-0x1F) + DEL — including \n and \t — so
  // newline-delimited presence wire format below is unambiguous and names
  // can't smuggle in formatting characters.
  const cleaned = s.replace(/[\x00-\x1F\x7F]/g, "").trim().slice(0, MAX_USERNAME_LEN);
  return cleaned || "Anonymous";
}

function normalizeTeam(value) {
  if (value === 0 || value === "0") return 0;
  if (value === 1 || value === "1") return 1;
  return null;
}

function normalizeBoolean(value) {
  return value === true || value === "true" || value === 1 || value === "1";
}

function normalizePresenceRevision(value) {
  return Number.isSafeInteger(value) && value > 0 ? value : 0;
}

function normalizeAudience(raw) {
  if (raw == null || raw === "") return "all";
  if (typeof raw !== "string") return null;
  const audience = raw.toLowerCase();
  return audience === "team" || audience === "all" ? audience : null;
}

// Build each recipient's snapshot separately: joining a match-wide chat room
// must not reveal pregame opponents. Lua permits wider disclosure only after
// observing gameplay for this match. See docs/learnings/chat-presence.md.
//
// Wire format: `members` is a single string with usernames joined by "\n".
// We don't ship a JSON array because the mod's Lua json decoder is
// intentionally flat-objects-only (see mod/OSPlus/scripts/json.lua header).
// sanitizeUsername strips all C0 controls, so "\n" is a safe delimiter.
//
// `presence` is server-out-only and intentionally absent from VALID_TYPES;
// clients never send it.
function broadcastPresence(room) {
  const members = rooms.get(room);
  if (!members) return;
  for (const recipient of members) {
    if (recipient.readyState !== 1) continue;
    const revealOpponents = recipient._revealOpponents === true;
    const hasPlayerTeam = !recipient._spectator &&
      (recipient._team === 0 || recipient._team === 1);
    const list = [];
    for (const client of members) {
      if (client.readyState !== 1) continue;
      const samePlayerTeam = hasPlayerTeam && !client._spectator &&
        client._team === recipient._team;
      if (client === recipient || revealOpponents || samePlayerTeam) {
        if (client._username) list.push(client._username);
      }
    }
    recipient.send(JSON.stringify({
      type: "presence", room, members: list.join("\n"),
      presenceRevision: recipient._presenceRevision, revealOpponents,
    }));
  }
}

function broadcast(room, sender, message) {
  const members = rooms.get(room);
  if (!members) return;
  const raw = JSON.stringify(message);
  for (const client of members) {
    if (client !== sender && client.readyState === 1) client.send(raw);
  }
}

function broadcastChat(room, sender, message) {
  const members = rooms.get(room);
  if (!members) return;
  const raw = JSON.stringify(message);
  for (const client of members) {
    if (client === sender || client.readyState !== 1) continue;
    if (message.audience === "team" && client._team !== message.targetTeam) continue;
    client.send(raw);
  }
}

function removeFromRoom(ws) {
  ws._revealOpponents = false;
  ws._presenceRevision = 0;
  if (!ws._room) return;
  const room = ws._room;
  const members = rooms.get(room);
  if (members) {
    members.delete(ws);
    if (members.size === 0) {
      rooms.delete(room);
      log(`[ROOM] ${room} dissolved (empty)`);
    } else {
      log(`[ROOM] ${room} now has ${members.size} member(s)`);
      // Tell the survivors that someone left.
      broadcastPresence(room);
    }
  }
  ws._room = null;
}

// === Persistence (REST /api/*) ================================================

const api = createApi({ dataDir: DATA_DIR, log });
const updates = createUpdates({
  log,
  repo: RELEASE_REPO,
  assetName: RELEASE_ASSET,
  cacheTtlMs: RELEASE_CACHE_TTL_MS,
  githubToken: GITHUB_TOKEN,
  overrideVersion: RELEASE_OVERRIDE_VERSION,
});

// === HTTP server ==============================================================

const httpServer = http.createServer(async (req, res) => {
  // Public update metadata and authenticated /api/* persistence are separate
  // modules. Each returns true only when it owns the request.
  try {
    if (await updates.handleHttp(req, res)) return;
    if (await api.handleHttp(req, res)) return;
  } catch (err) {
    log(`[ERR] HTTP dispatch crashed: ${err && err.stack ? err.stack : String(err)}`);
    if (!res.headersSent) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "internal error" }));
    }
    return;
  }

  if (req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({
      status: "ok",
      uptime_sec: Math.floor(process.uptime()),
      rooms: rooms.size,
      connections: wss.clients.size,
    }));
    return;
  }
  res.writeHead(404);
  res.end();
});

// === WS server ================================================================

const wss = new WebSocketServer({
  server: httpServer,
  maxPayload: MAX_PAYLOAD_BYTES,
  verifyClient: (info, done) => {
    if (!RELAY_TOKEN) return done(true);
    try {
      const url = new URL(info.req.url, "http://x");
      if (url.searchParams.get("t") === RELAY_TOKEN) return done(true);
    } catch { /* fall through */ }
    log(`[AUTH] reject from ${getClientIp(info.req)}: bad token`);
    done(false, 401, "Unauthorized");
  },
});

wss.on("connection", (ws, req) => {
  const ip = getClientIp(req);
  const ipCount = (connsPerIp.get(ip) || 0) + 1;
  if (ipCount > MAX_CONNS_PER_IP) {
    log(`[LIMIT] ${ip} exceeded conn cap (${ipCount})`);
    ws.close(1008, "connection cap");
    return;
  }
  connsPerIp.set(ip, ipCount);

  ws._room = null;
  ws._ip = ip;
  ws._username = null;
  ws._team = null;
  ws._spectator = false;
  ws._revealOpponents = false;
  ws._presenceRevision = 0;
  ws._rateCount = 0;
  ws._rateWindowStart = Date.now();

  log(`[CONN] +${ip} (total: ${wss.clients.size}, from-ip: ${ipCount})`);

  ws.on("message", (raw) => {
    const now = Date.now();
    if (now - ws._rateWindowStart > RATE_WINDOW_MS) {
      ws._rateCount = 0;
      ws._rateWindowStart = now;
    }
    ws._rateCount++;
    if (ws._rateCount > MAX_MSG_RATE) {
      log(`[LIMIT] ${ws._ip} rate exceeded`);
      ws.close(1008, "rate limit");
      return;
    }

    let msg;
    try { msg = JSON.parse(raw); }
    catch {
      ws.send(JSON.stringify({ type: "error", error: "invalid JSON" }));
      return;
    }
    if (!msg || typeof msg.type !== "string" || !VALID_TYPES.has(msg.type)) {
      ws.send(JSON.stringify({ type: "error", error: "invalid type" }));
      return;
    }

    switch (msg.type) {
      case "join": {
        removeFromRoom(ws);
        let room;
        if (msg.room) {
          room = String(msg.room).toUpperCase();
          if (!ROOM_CODE_RE.test(room)) {
            ws.send(JSON.stringify({ type: "error", error: "invalid room code" }));
            return;
          }
        } else {
          room = generateRoomCode();
        }
        ws._username = sanitizeUsername(msg.username);
        ws._team = normalizeTeam(msg.team);
        ws._spectator = normalizeBoolean(msg.spectator);
        ws._revealOpponents = msg.revealOpponents === true;
        ws._presenceRevision = normalizePresenceRevision(msg.presenceRevision);
        if (!rooms.has(room)) rooms.set(room, new Set());
        rooms.get(room).add(ws);
        ws._room = room;
        ws.send(JSON.stringify({ type: "joined", room }));
        const teamLabel = ws._spectator ? "spectator" : (ws._team === null ? "unknown team" : `team ${ws._team + 1}`);
        log(`[ROOM] ${ws._ip} (${ws._username}, ${teamLabel}) joined ${room} (${rooms.get(room).size} member(s))`);
        broadcastPresence(room);
        break;
      }

      case "leave": {
        const prev = ws._room;
        removeFromRoom(ws);
        ws.send(JSON.stringify({ type: "left", room: prev }));
        break;
      }

      case "chat": {
        if (!ws._room) { ws.send(JSON.stringify({ type: "error", error: "not in a room" })); return; }
        msg.text = sanitizeChatText(msg.text);
        if (!msg.text) return;
        const audience = normalizeAudience(msg.audience);
        if (!audience) { ws.send(JSON.stringify({ type: "error", error: "invalid audience" })); return; }
        msg.audience = audience;
        if (audience === "team") {
          const targetTeam = normalizeTeam(msg.targetTeam);
          const fallbackTeam = normalizeTeam(ws._team);
          msg.targetTeam = targetTeam === null ? fallbackTeam : targetTeam;
          if (msg.targetTeam === null) {
            ws.send(JSON.stringify({ type: "error", error: "invalid target team" }));
            return;
          }
          if (!ws._spectator && msg.targetTeam !== fallbackTeam) {
            ws.send(JSON.stringify({ type: "error", error: "players cannot target the other team" }));
            return;
          }
        } else {
          delete msg.targetTeam;
        }
        broadcastChat(ws._room, ws, msg);
        break;
      }

      case "ping": {
        if (!ws._room) { ws.send(JSON.stringify({ type: "error", error: "not in a room" })); return; }
        broadcast(ws._room, ws, msg);
        break;
      }
    }
  });

  ws.on("close", () => {
    removeFromRoom(ws);
    const remaining = (connsPerIp.get(ws._ip) || 1) - 1;
    if (remaining <= 0) connsPerIp.delete(ws._ip);
    else connsPerIp.set(ws._ip, remaining);
    log(`[CONN] -${ws._ip} (total: ${wss.clients.size})`);
  });

  ws.on("error", (err) => {
    log(`[ERR] ${ws._ip}: ${err.message}`);
  });
});

// === Lifecycle ================================================================

httpServer.listen(PORT, HOST, () => {
  log(`[RELAY] Listening on ${HOST}:${PORT}`);
  log(`[RELAY] WS auth:             ${RELAY_TOKEN ? "ON (token required)" : "OFF (open)"}`);
  log(`[RELAY] Trust X-Forwarded-For: ${TRUST_PROXY ? "yes" : "no"}`);
  log(`[RELAY] WS limits:           ${MAX_PAYLOAD_BYTES}B/msg, ${MAX_CONNS_PER_IP} conns/ip, ${MAX_MSG_RATE} msg/s`);
  log(`[RELAY] Data dir:            ${DATA_DIR}`);
  log(`[RELAY] Update cache TTL:    ${RELEASE_CACHE_TTL_MS}ms`);
});

function shutdown(sig) {
  log(`[SHUTDOWN] ${sig} received, closing ${wss.clients.size} client(s)`);
  for (const ws of wss.clients) ws.close(1001, "server shutting down");
  httpServer.close(() => {
    log(`[SHUTDOWN] HTTP closed, closing DB`);
    api.close();
    log(`[SHUTDOWN] DB closed, exiting`);
    process.exit(0);
  });
  setTimeout(() => { log("[SHUTDOWN] hard exit"); process.exit(1); }, 5000);
}
process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT",  () => shutdown("SIGINT"));
